apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  labels:
    app: mysql
    tier: backend
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
    tier: backend