apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  labels:
    app: discovery-server
    tier: frontend
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: discovery-server
    tier: frontend